FROM nginx:1.27.4

RUN rm /etc/nginx/conf.d/default.conf \
    && apt-get update \
    && apt-get install -y --no-install-recommends openssl \
    && rm -rf /var/lib/apt/lists/*

COPY nginx_prod.conf /etc/nginx/conf.d/nginx_prod.conf
